var jsonDocument = [
  {
    "type": "draw2d.shape.basic.Rectangle",
    "id": "jalihouseLayerProtection0",
    "x": 215,
    "y": 314,
    "width": 420,
    "height": 220,
    "alpha": 1,
    "angle": 0,
    "userData": {},
    "cssClass": "draw2d_shape_basic_Rectangle",
    "ports": [],
    "bgColor": "#FFFFFF",
    "color": "#000000",
    "stroke": 1,
    "radius": 0,
    "dasharray": null
  },
  {
    "type": "GraphLang.Shapes.Basic.Loop.Multilayered",
    "id": "86345846-a99a-750e-8f89-5af9f63622f7",
    "x": 215,
    "y": 314,
    "width": 420,
    "height": 220,
    "alpha": 1,
    "angle": 0,
    "userData": {
      "executionOrder": 1,
      "wasTranslatedToCppCode": false
    },
    "cssClass": "GraphLang_Shapes_Basic_Loop_Multilayered",
    "ports": [],
    "bgColor": "#F0F0F0",
    "color": "#1B1B1B",
    "stroke": 2,
    "radius": 0,
    "dasharray": null,
    "myLabel": "myLabel changed",
    "graphlangLayerOwner": "...here should be id of owner parent....."
  },
  {
    "type": "draw2d.shape.composite.Jailhouse",
    "id": "jailhouseLayer3",
    "x": 215,
    "y": 314,
    "width": 420,
    "height": 220,
    "alpha": 1,
    "angle": 0,
    "userData": {},
    "cssClass": "draw2d_shape_composite_Jailhouse",
    "ports": [],
    "bgColor": "#88BB66",
    "color": "#00FF00",
    "stroke": 1,
    "radius": 0,
    "dasharray": null
  },
  {
    "type": "draw2d.shape.composite.Jailhouse",
    "id": "jailhouseLayer2",
    "x": 215,
    "y": 314,
    "width": 420,
    "height": 220,
    "alpha": 1,
    "angle": 0,
    "userData": {},
    "cssClass": "draw2d_shape_composite_Jailhouse",
    "ports": [],
    "bgColor": "#FFFF00",
    "color": "#FF0000",
    "stroke": 1,
    "radius": 0,
    "dasharray": null
  },
  {
    "type": "draw2d.shape.composite.Jailhouse",
    "id": "jailhouseLayer1",
    "x": 215,
    "y": 314,
    "width": 420,
    "height": 220,
    "alpha": 1,
    "angle": 0,
    "userData": {},
    "cssClass": "draw2d_shape_composite_Jailhouse",
    "ports": [],
    "bgColor": "#0000FF",
    "color": "#FF0000",
    "stroke": 1,
    "radius": 0,
    "dasharray": null
  }
];
